# Графы

Граф — это нелинейная структура данных, состоящая из узлов и рёбер. Узлы иногда также называют вершинами, а рёбра — линиями или дугами, которые соединяют любые две вершины графа. Более формально граф можно определить как структуру, состоящую из конечного набора вершин (или узлов) и набора рёбер, которые соединяют пару вершин.

G := (V, E) , где V — непустое множество вершин или узлов, а E — множество пар вершин, называемых рёбрами. Если вершины в ребрах упорядочены, такой граф называется ориентированным. Если вершины в ребрах неупорядочены, такой граф называется неориентированным.

![](https://img1.teletype.in/files/82/94/8294a310-1ad3-43cb-b1d3-d3a6b3493af0.png)

В приведенном выше графе множество вершин V = {0,1,2,3,4} и множество ребер E = {01, 12, 23, 34, 04, 14, 13}. Наиболее часто используемыми представлениями графа являются следующие два типа:
- матрица смежности;
- список смежности.

## Матрица смежности

Матрица смежности — это двумерный массив размером V на V, где V — количество вершин в графе. Пусть двумерный массив будет adj[][], слот adj[i][j] = 1 означает, что существует ребро из вершины i в вершину j. Матрица смежности для неориентированного графа всегда симметрична; она также используется для представления взвешенных графов. Если adj[i][j] = w, то существует ребро из вершины i в вершину j с весом w.

In [23]:
import numpy as np
import networkx as nx

In [28]:
# Простое представление графа с помощью матрицы смежности
class Graph:
	def __init__(self,numvertex):
		self.adj_matrix = [[-1]*numvertex for x in range(numvertex)]
		self.numvertex = numvertex
		self.vertices = {}
		self.verticeslist =[0]*numvertex

	def set_vertex(self,vtx,id):
		if 0<=vtx<=self.numvertex:
			self.vertices[id] = vtx
			self.verticeslist[vtx] = id

	def set_edge(self,frm,to,cost=0):
		frm = self.vertices[frm]
		to = self.vertices[to]
		self.adj_matrix[frm][to] = cost

		# для направленного графа не добавлять это:
		self.adj_matrix[to][frm] = cost

	def get_vertex(self):
		return self.verticeslist

	def get_edges(self):
		edges = []
		for i in range (self.numvertex):
			for j in range (self.numvertex):
				if (self.adj_matrix[i][j] != -1):
					edges.append((self.verticeslist[i],
					self.verticeslist[j],
					self.adj_matrix[i][j]))
		return edges

	def get_matrix(self):
		return np.array(self.adj_matrix)

G = Graph(6)
G.set_vertex(0,'a')
G.set_vertex(1,'b')
G.set_vertex(2,'c')
G.set_vertex(3,'d')
G.set_vertex(4,'e')
G.set_vertex(5,'f')
G.set_edge('a','e')
G.set_edge('a','c')
G.set_edge('c','b')
G.set_edge('b','e')
G.set_edge('e','d')
G.set_edge('f','e')

In [22]:
print("Вершины графа:")
print(G.get_vertex())

print("Рёбра графа:")
print(G.get_edges())

print("Матрица смежности:")
print(G.get_matrix())

Вершины графа:
['a', 'b', 'c', 'd', 'e', 'f']
Рёбра графа:
[('a', 'c', 20), ('a', 'e', 10), ('b', 'c', 30), ('b', 'e', 40), ('c', 'a', 20), ('c', 'b', 30), ('d', 'e', 50), ('e', 'a', 10), ('e', 'b', 40), ('e', 'd', 50), ('e', 'f', 60), ('f', 'e', 60)]
Матрица смежности:
[[-1 -1 20 -1 10 -1]
 [-1 -1 30 -1 40 -1]
 [20 30 -1 -1 -1 -1]
 [-1 -1 -1 -1 50 -1]
 [10 40 -1 50 -1 60]
 [-1 -1 -1 -1 60 -1]]


## Список смежности


Для его создания используется массив списков. Размер массива равен количеству вершин. Пусть массив представляет собой array[]. Запись array[i] представляет собой список вершин, смежных с вершиной i. Веса рёбер могут быть представлены в виде списков пар. Вот представление в виде списка смежности для графа выше.

![](https://img1.teletype.in/files/c2/0f/c20f6427-2a59-4ba3-9ac1-bb3cc4b22499.jpeg)

In [30]:
# Класс для представления списка смежности узла
class AdjNode:
	def __init__(self, data):
		self.vertex = data
		self.next = None


# Класс для представления графа.
# Граф - это список списков смежности.
# Размер массива равен кол-ву вершин "V".
class Graph:
	def __init__(self, vertices):
		self.V = vertices
		self.graph = [None] * self.V

	# Функция для добавления ребра в неориентированный граф
	def add_edge(self, src, dest):

		# Добавление узла к исходному узлу
		node = AdjNode(dest)
		node.next = self.graph[src]
		self.graph[src] = node

		# Добавление узла источника к узлу назначения
		# так как это неориентированный граф
		node = AdjNode(src)
		node.next = self.graph[dest]
		self.graph[dest] = node

	# Функция для вывода графа
	def print_graph(self):
		for i in range(self.V):
			print("Список смежности вершин {}\n начало".format(i), end="")
			temp = self.graph[i]
			while temp:
				print(" -> {}".format(temp.vertex), end="")
				temp = temp.next
			print(" \n")

if __name__ == "__main__":
	V = 5
	graph = Graph(V)
	graph.add_edge(0, 1)
	graph.add_edge(0, 4)
	graph.add_edge(1, 2)
	graph.add_edge(1, 3)
	graph.add_edge(1, 4)
	graph.add_edge(2, 3)
	graph.add_edge(3, 4)

	graph.print_graph()

Список смежности вершин 0
 начало -> 4 -> 1 

Список смежности вершин 1
 начало -> 4 -> 3 -> 2 -> 0 

Список смежности вершин 2
 начало -> 3 -> 1 

Список смежности вершин 3
 начало -> 4 -> 2 -> 1 

Список смежности вершин 4
 начало -> 3 -> 1 -> 0 



# Рекурсия

Процесс, в котором функция прямо или косвенно вызывает саму себя, называется рекурсией, а соответствующая функция — рекурсивной. Некоторые проблемы можно решить довольно легко, если использовать рекурсивные алгоритмы. Примерами таких задач являются Ханойские башни (TOH), обходы деревьев и т.д.

## Что такое базовое условие в рекурсии

В рекурсивной программе дается решение базового случая, а решение большей задачи разбивается на меньшие.

В приведённом ниже примере определён базовый случай для n < = 1, и случай с большим числом может быть решён путём преобразования числа в меньшее, пока не будет достигнут базовый случай.

In [31]:
def fact(n):
    # базовый случай
    if (n <= 1):
        return 1
    else:
        res = n*fact(n-1)
        print('res', res)
        return res

In [32]:
fact(4)

res 2
res 6
res 24


24

# Бинарное дерево (Binary tree)

Дерево — это иерархическая структура данных, которая выглядит так, как показано ниже.

```markdown
   дерево
    ----
      j    <-- корень
    /   \
   f      k  
 /   \      \
a     h      z    <-- листья
```

Самый верхний узел дерева называется корнем, а самые нижние узлы или узлы, не имеющие детей, называются листовыми узлами. Узлы, которые находятся непосредственно под узлом, называются его детьми, а узлы, которые находятся непосредственно над узлом, называются его родителем.

Бинарное дерево — это дерево, элементы которого могут иметь два дочерних элемента. Поскольку каждый элемент бинарного дерева может иметь только 2 дочерних элемента, мы обычно называем их просто левый и правый. Узел бинарного дерева содержит следующие части:
- Данные
- Указатель на левый дочерний элемент
- Указатель на правый дочерний элемент

Давайте создадим дерево с четырьмя узлами. Предположим, что структура дерева выглядит следующим образом:

```markdown
  дерево
    ----
     1    <-- корень
   /   \
  2     3  
 /  
4
```

In [ ]:
# класс как узел бинарного дерева
class Node:
	def __init__(self,key):
		self.left = None
		self.right = None
		self.val = key


# создаём узел
root = Node(1)
''' вот что должно получиться:
	 1
	/ \
 None None'''

root.left = Node(2)
root.right = Node(3)

'''
	 1
	/ \
 2   3
/ \ / \
None None None None'''


root.left.left = Node(4)
'''
	   1
  	/	 \
   2	  3
  / \	 / \
4  None None None
/ \
None None'''

## Обход бинарного дерева

Деревья можно обходить различными способами. Ниже перечислены наиболее часто используемые. Рассмотрим следующее дерево:

```markdown
   дерево
    ----
     1    <-- корень
   /   \
  2     3  
 / \
4   5
```

### Обход дерева в глубину

- **Центрированный** (левое поддерево, корень, правое поддерево) : 4 2 5 1 3
- **Прямой** (корень, левое поддерево, правое поддерево) : 1 2 4 5 3
- **Обратный** (левое поддерево, правое поддерево, корень) : 4 5 2 3 1

**Центрированный алгоритм**
- Пройти по левому поддереву, т.е. вызвать Inorder(left-subtree).
- Зайти в корень.
- Пройти по правому поддереву, т.е. вызвать Inorder(right-subtree).

**Прямой алгоритм**
- Зайти в корень.
- Обратиться к левому поддереву, т.е. вызвать Preorder(left-subtree).
- Пройти по правому поддереву, т.е. вызвать Preorder(right-subtree).

**Обратный алгоритм**
- Обратиться к левому поддереву, т.е. вызвать Postorder(left-subtree).
- Пройти по правому поддереву, т.е. вызвать Postorder(right-subtree).
- Зайти в корень.

In [33]:
# узел бинарного дерева
class Node:
	def __init__(self, key):
		self.left = None
		self.right = None
		self.val = key


# ф-ия для обхода дерева по
# центрированному алгоритму
def print_inorder(root):
	if root:
		# рекурсивно возвращаемся к левому поддереву
		print_inorder(root.left)

		# выводим данные узла
		print(root.val),

		# рекурсивно возвращаемся к правому поддереву
		print_inorder(root.right)

# ф-ия для обхода дерева по
# обратному алгоритму
def print_postorder(root):
	if root:

		# рекурсивно возвращаемся к левому поддереву
		print_postorder(root.left)

		# рекурсивно возвращаемся к правому поддереву
		print_postorder(root.right)

		# выводим данные узла
		print(root.val),

# ф-ия для обхода дерева по
# прямому алгоритму
def print_preorder(root):
	if root:

		# сначала выводим данные
		print(root.val),

		# рекурсивно возвращаемся к левому поддереву
		print_preorder(root.left)

		# рекурсивно возвращаемся к правому поддереву
		print_preorder(root.right)


# запускаем
root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)
print("Обход по прямому алгоритму:")
print_preorder(root)

print("\nОбход по центрированному алгоритму:")
print_inorder(root)

print("\nОбход по обратному алгоритму:")
print_postorder(root)

Обход по прямому алгоритму:
1
2
4
5
3

Обход по центрированному алгоритму:
4
2
5
1
3

Обход по обратному алгоритму:
4
5
2
3
1


```markdown
   дерево
    ----
     1    <-- корень
   /   \
  2     3  
 / \
4   5
```

### Обход дерева в ширину

Для приведённого выше дерева порядок следования уровней следующий: 1 2 3 4 5.

Сначала посещается сам узел, а затем его дочерние узлы помещаются в очередь. Ниже приведён алгоритм для этого:
- Создать пустую очередь q
- temp_node = root /*начать с корня*/
- Запустить цикл while пока temp_node is not None
  - вывести данные в temp_node
  - записать дочерние узлы temp_node (сначала левый, затем правый) в q
  - удалить узел из q

In [34]:
# обход дерева в ширину с помощью очереди
# задаём структуру узла
class Node:

	def __init__(self ,key):
		self.data = key
		self.left = None
		self.right = None

# итеративный метод вывода
# высоты дерева
def print_level_order(root):
	if root is None:
		return

	# создаём пустую очередь
	queue = []

	# добавляем узел
	queue.append(root)

	while(len(queue) > 0):

		# выводим первый элемент в очереди
		# и убираем его
		print(queue[0].data)
		node = queue.pop(0)

		# добавляем в очередь левое поддерево
		if node.left is not None:
			queue.append(node.left)

		# добавляем в очередь правое поддерево
		if node.right is not None:
			queue.append(node.right)

# запускаем шайтан-код
root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)

print("Обходим дерево по ширине:")
print_level_order(root)

Обходим дерево по ширине:
1
2
3
4
5


# Бинарное дерево поиска (Binary Search Tree)

Это основанная на узлах двоичная древовидная структура данных, обладающая следующими свойствами:
- Левое поддерево узла содержит только узлы с ключами, меньшими, чем ключ узла.
- Правое поддерево узла содержит только узлы с ключами, большими, чем ключ узла.
- Каждое левое и правое поддерево также должно быть двоичным деревом поиска.

![](https://media.geeksforgeeks.org/wp-content/uploads/BSTSearch.png)

Такие свойства дерева обеспечивают упорядочивание ключей, поэтому операции поиска, нахождение минимума и максимума могут быть выполнены быстро. Если порядка нет, то для поиска заданного ключа может потребоваться сравнение каждого ключа.

## Поиск элемента

- Начинаем с корня.
- Сравниваем искомый элемент с корнем. Если он меньше корня, то выполняем перебор слева, если больше, то справа.
- Если искомый элемент найден, возвращаем True, иначе — False.

In [ ]:
# ф-ия поиска ключа
def search(root,key):

	# Базовый случай: узел пуст или ключ в узле
	if root is None or root.val == key:
		return root

	# Ключ больше того, что в узле
	if root.val < key:
		return search(root.right,key)

	# Ключ меньше того, что в узле
	return search(root.left,key)

## Вставка ключа

- Начинаем с корня.
- Сравниваем вставляемый элемент с корнем, если он меньше, чем корень, то выполняем перебор слева, иначе — выполняем перебор элементов справа.
- Достигнув конца, вставляем этот узел слева (если он меньше текущего), иначе — справа.

In [ ]:
# задаём структуру узла
class Node:
	def __init__(self, key):
		self.left = None
		self.right = None
		self.val = key

# ф-ия вставки нового узла с
# заданным ключом
def insert(root, key):
	if root is None:
		return Node(key)
	else:
		if root.val == key:
			return root
		elif root.val < key:
			root.right = insert(root.right, key)
		else:
			root.left = insert(root.left, key)
	return root

# ф-ия для центрированного обхода дерева
def inorder(root):
	if root:
		inorder(root.left)
		print(root.val)
		inorder(root.right)


# запускаем
# чтобы создать такое дерево:
#    50
#   /	\
# 30	 70
# / \    / \
#20 40  60 80

r = Node(50)
r = insert(r, 30)
r = insert(r, 20)
r = insert(r, 40)
r = insert(r, 70)
r = insert(r, 60)
r = insert(r, 80)

inorder(r)

# Обходы графа

## Обход в ширину (Breadth-First Search или BFS)

Обход в ширину для графа похож на аналогичный алгоритм для дерева. Единственная загвоздка в том, что в отличие от деревьев, графы могут содержать циклы, поэтому мы можем прийти к одному и тому же узлу снова. Чтобы избежать обработки узла более одного раза, мы используем массив из булевых значений «посещён/не посещён». Для простоты предполагается, что все вершины достижимы из начальной вершины.

Например, в следующем графе мы начинаем обход с вершины 2. Когда мы приходим к вершине 0, мы ищем все смежные с ней вершины. 2 также является смежной вершиной 0. Если мы не пометим посещённые вершины, то 2 будет обработана снова, и процесс зациклится. BFS следующего графа — 2, 0, 3, 1.

![](https://media.geeksforgeeks.org/wp-content/uploads/bfs-5.png)

In [35]:
from collections import defaultdict

# Этот класс представляет направленный граф,
# построенный с помощью списка смежности
class Graph:
	# конструктор
	def __init__(self):

		# словарь для хранения графа
		self.graph = defaultdict(list)

	# ф-ия для добавления ребра к графу
	def add_edge(self,u,v):
		self.graph[u].append(v)

	# ф-ия для печати результата обхода графа
	def BFS(self, s):

		# Пометить все вершины как не посещённые
		visited = [False] * (max(self.graph) + 1)

		# Создание очереди для BFS
		queue = []

		# Пометить исходный узел как посещённый
		# и поставить его в очередь
		queue.append(s)
		visited[s] = True

		while queue:

			# Удалить вершину из
			# очереди и вывести её
			s = queue.pop(0)
			print(s, end = " ")

			# Получить все смежные вершины отложенной вершины s.
			# Если смежная вершина не была посещена, то пометить
			# её посещённой и поставить в очередь
			for i in self.graph[s]:
				if visited[i] == False:
					queue.append(i)
					visited[i] = True

# магия
g = Graph()
g.add_edge(0, 1)
g.add_edge(0, 2)
g.add_edge(1, 2)
g.add_edge(2, 0)
g.add_edge(2, 3)
g.add_edge(3, 3)

print("Обход в ширину (начиная с вершины 2)")
g.BFS(2)

Обход в ширину (начиная с вершины 2)
2 0 3 1 

## Обход в глубину (Depth First Search или DFS)

Алгоритм следующий:
- Создать рекурсивную функцию, которая принимает индекс узла и список visited.
- Пометить текущий узел как посещённый и вывести его на печать.
- Пройти по всем соседним и не помеченным узлам и вызвать рекурсивную функцию с индексом соседнего узла.

In [36]:
from collections import defaultdict

# Этот класс представляет направленный граф,
# построенный с помощью списка смежности
class Graph:

	# конструктор
	def __init__(self):

		# словарь для хранения графа
		self.graph = defaultdict(list)

	# ф-ия для добавления ребра к графу
	def add_edge(self, u, v):
		self.graph[u].append(v)

	# ф-ия для ф-ии DFS
	def DFSUtil(self, v, visited):

		# помечаем узел как посещённый
		# и выводим его
		visited.add(v)
		print(v, end=' ')

		# Повторить для всех вершин,
		# смежных с данной вершиной
		for neighbour in self.graph[v]:
			if neighbour not in visited:
				self.DFSUtil(neighbour, visited)

	# ф-ия для обхода графа в глубину.
	# в ней используется рекурсивная ф-ия DFSUtil()
	def DFS(self, v):

		# создаём множество, где хранятся все
		# посещённые вершины
		visited = set()

		# вызов рекурсивной спромогательной ф-ии
		# для вывода результата обхода графа в глубину
		self.DFSUtil(v, visited)


# создаём граф
# как на диаграмме выше
g = Graph()
g.add_edge(0, 1)
g.add_edge(0, 2)
g.add_edge(1, 2)
g.add_edge(2, 0)
g.add_edge(2, 3)
g.add_edge(3, 3)

print("Обход графа в глубину (начиная с вершины 2)")
g.DFS(2)

Обход графа в глубину (начиная с вершины 2)
2 0 1 3 